#!/bin/bash

RA=($(seq 0 180 180))
DEC=($(seq 0 -15 -90))

for i in "${RA[@]}"
do
    for j in "${DEC[@]}"
    do
         python RFIsim.py --ntime 225 --nant 4 --save_dir 'output_data' --noise $1 --gpu $2 --ra $i --dec $j
    done
done
