from setuptools import setup, find_packages

setup(name='RFIsim',
      version='0.2.0',
      description='Radio Frequency Interference (RFI) simulations for radio interferometers',
      url='http://github.com/chrisfinlay/RFIsim',
      author='Chris Finlay',
      author_email='cfinlay@ska.ac.za',
      license='MIT',
      packages=find_packages(),
      package_data={'RFIsim': ['rfi/sat_sim/TLEs/norad_ids.npy',
                               'rfi/sat_sim/TLEs/sat_names.csv']},
      scripts=['bin/RFIsim'],
      install_requires=['numpy',
                        'dask[array]',
                        'zarr',
                        'skyfield',
                        'spacetrack',
                        'pytz',
                        'tzwhere',
                        'pandas',
                        'PyYaml',
                        'fsspec>=0.3.3',
                       ],
      zip_safe=False)
